# General
seed: 42
device: "cuda"  # or "cpu"

# Paths
data_dir: "/home/sgu/datasets/XNLI/fr"

# Model
# when changing model, just change the value of model_name and tokenizer_name, 
# for models already in HuggingFace like camembert-base, model_name and tokenizer_name is the same,
# if it's a local model not yet in the HuggingFace,the model path and tokenizer path on local server may be same or different.
# so just put corresponding model and tokenizer path
# eg: "/home/sgu/models/Text_Base_fr_OSCAR_camtok/HuggingFace"
model_name: "/home/sgu/models/Text_Base_fr_4GB_v1/HuggingFace"
tokenizer_name: "/home/sgu/models/Text_Base_fr_4GB_v1/HuggingFace"
max_seq_length: 512
num_classes: 3 # entailment / contradiction / neutral
dropout: 0.1

# Training
batch_size: 16
num_epochs: 30
learning_rates: [1e-5, 5e-5, 1e-6, 5e-6]
early_stopping_patience: 3

# Dataset
datasets: ["train", "dev", "test"]
