name: sequence-classification
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - scikit-learn
  - tqdm
  - sacremoses
  - timm
  - pyyaml
  - sentencepiece
  - protobuf
  - pip:
      - torch 
      - git+https://github.com/formiel/transformers.git@pantagruel
