# General
seeds: [1, 1234]
device: "cuda"  # or "cpu"

# Paths
data_dir: "/home/qguan/datasets/PSWS-X"
 

# HuggingFace settings (optional)
# You can set the token directly here, or use environment variable HF_TOKEN
# hf_token: "your_huggingface_token_here"

# Model
# when changing model, just change the value of model_name and tokenizer_name, 
# for models already in HuggingFace like camembert-base, model_name and tokenizer_name is the same,
# if it's a local model not yet in the HuggingFace,the model path and tokenizer path on local server may be same or different.
# so just put corresponding model and tokenizer path
# eg: "/home/sgu/models/Text_Base_fr_OSCAR_camtok/HuggingFace"
model_name: "PantagrueLLM/camembert-base-wikipedia-4gb-weight-fix"
tokenizer_name: "PantagrueLLM/camembert-base-wikipedia-4gb-weight-fix"
max_seq_length: 512
num_classes: 2
dropout: 0.1
add_pooling_layer: False
use_pooler: False

# Training
batch_size: 16
num_epochs: 30
learning_rates: [1e-5]
early_stopping_patience: 5

# Dataset
datasets: ["train", "dev", "test"]
